title: O kávě
baseURL: https://eloquent-wiles-d75ba3.netlify.com/
languageCode: cs-cz
publishDir: public
googleAnalytics: "UA-139431118-1"

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

